### ISSUE TITLE
New harmonized global above and belowground biomass carbon density data

### ISSUE THREAD

**Issue by climate-dude** [rubisco-sfa/ILAMB-Data#10]
A new synthesized dataset provides separate maps of global above and belowground biomass carbon density estimates across a wide range of vegetation types in 2010 at 300m resolution with quantified uncertainty. The relevant paper, published April 6, 2020, is:

Spawn, Seth A., Clare C. Sullivan, Tyler J. Lark, and Holly K. Gibbs (2020), Harmonized global maps of above and belowground biomass carbon density in the year 2010, _Sci Data_, 7, 112, doi:[10.1038/s41597-020-0444-4](https://doi.org/10.1038/s41597-020-0444-4)

The authors compare these new estimates with the IPCC Tier-1 live C reported by Ruesh and Gibbs (2008) for year 2000, but they caution against using these differences as an indication of biomass change across that period since the products were produced by different methods.

**Comment by nocollier** [comment]
https://data.ess-dive.lbl.gov/view/doi:10.15485/1463800

**Comment by nocollier** [comment]
ae7dbbb
