### ISSUE TITLE
Add WECANN GPP as an alternate dataset

### ISSUE THREAD

**Issue by climate-dude** [rubisco-sfa/ILAMB-Data#14]
The WECANN data provides an alternate global dataset for GPP and turbulent fluxes, which would be nice to have in ILAMB.

Alemohammad, S. H., B. Fang, A. G. Konings, F. Aires, J. K. Green, J. Kolassa, D. Miralles, C. Prigent, and P. Gentine (2017), Water, Energy, and Carbon with Artificial Neural Networks (WECANN): A statistically based estimate of global surface turbulent fluxes and gross primary productivity using solar-induced fluorescence, Biogeosciences, 14(18), 4101–4124, doi:10.5194/bg-14-4101-2017.

Data available at https://avdc.gsfc.nasa.gov/pub/data/project/WECANN/

**Comment by nocollier** [comment]
Added in 726635e, see [these](https://www.climatemodeling.org/~nate/ILAMB-Test/) results for sample run.
