### ISSUE TITLE
Wrong  Jung et al. reference for FLUXCOM datasets

### ISSUE THREAD

**Issue by climate-dude** [rubisco-sfa/ILAMB-Data#15]
It appears that the preferred references for FLUXCOM datasets are:

Jung, M., S. Koirala, U. Weber, K. Ichii, F. Gans, Gustau-Camps-Valls, D. Papale, C. Schwalm, G. Tramontana, and M. Reichstein (2019), The FLUXCOM ensemble of global land-atmosphere energy fluxes, _Scientific Data_, 6(1), 74, doi:[10.1038/s41597-019-0076-8](https://doi.org/10.1038/s41597-019-0076-8).

Tramontana, G., M. Jung, C.R. Schwalm, K. Ichii, G. Camps-Valls, B. Raduly, M. Reichstein, M.A. Arain, A. Cescatti, G. Kiely, L. Merbold, P. Serrano-Ortiz, S. Sickert, S. Wolf, and D. Papale (2016), Predicting carbon dioxide and energy fluxes across global FLUXNET sites with regression algorithms, _Biogeosciences_, 13, 4291-4313, doi:[10.5194/bg-13-4291-2016](https://doi.org/10.5194/bg-13-4291-2016).

Our data information includes the correct Tramontana et al. (2016) reference, but points to a less-useful Jung et al. (2017) reference instead of the Jung et al. (2019) reference above.

Our FLUXCOM datasets should be regenerated with the correct Jung et al. (2019) reference, replacing Jung et al. (2017).

**Comment by mmu2019** [comment]
Hi Forrest,

The current references signed with our FluxCom was obtained from FluxCom
data site. I didn't find their paper referring to Jung et al. 2016, thus I
found their new paper Jung et al. 2019.
Sorry about that.

https://doi.org/doi:10.17871/FLUXCOM_RS_METEO_CRUNCEPv6_1980_2013_v1


Mingquan

**Comment by nocollier** [comment]
Fixed in 8091326, will regenerate and be included in the next rerun.
