### ISSUE TITLE
FLUXNET-CH4 eddy covariance dataset

### ISSUE THREAD

**Issue by nocollier** [rubisco-sfa/ILAMB-Data#22]
Chang, K.-Y., Riley, W., Collier, N., McNicol, G., Fluet-Chouinard, E., Knox, S., Jackson, R., Poulter, B., Saunois, M., Zhu, Q.: Multi-model ensemble does not fill the gaps in sparse wetland methane observations, In review, Global Biogeochemical Cycles.

**Comment by nocollier** [comment]
@ckychang This dataset is from your recent publication correct? You have the integration finished and have run it against models, we are just waiting for the data to be formally ingested into FLUXNET such that it is publically available?

**Comment by ckychang** [comment]
@nocollier Yes, and I will reach out to you to figure out what format should be provided in this dataset. I wrote those site-level measurements in (time, data, FCH4) axes in netcdf formant as of now, but could include uncertainty range later if that's preferred.

**Comment by nocollier** [comment]
@ckychang I just wanted to touch base with you about this as we have had some community members ask. Is it ok to add this to our configure file and include the data in our comparisons?

**Comment by nocollier** [comment]
From a recent email exchange with @ckychang . The relevant CMIP variable is `wetlandCH4` however the variable attributes seem to indicated that while the methane is from the wetlands, the flux has been averaged over the grid cell. Note there is no `area: mean where wetlands time:mean` in the cell_methods:

```
wetlandCH4:cell_measures = "area: areacella" ;
wetlandCH4:cell_methods = "area: mean where land time: mean" ;
wetlandCH4:comment = "Net upward flux of methane (NH4) from wetlands (areas where water covers the soil, or is present either at or near the surface of the soil all year or for varying periods of time during the year, including during the growing season). "
```

which is required to be comparable to the CH4 product. I wonder if this is a case that what was done was just mislabeled? Otherwise we will need to compute `wetlandCH4 * sftlf / wetlandfraction` to make the fluxes comparable and I am not sure if that is even an output?

**Comment by nocollier** [comment]
Dave Lawrence commented that probably the models are reporting the net flux averaged over the land portion of the grid cell. It may just be a discrepancy that we cannot do anything about.
