### ISSUE TITLE
missing GBAF datasets

### ISSUE THREAD

**Issue by XUEYANZZZ** [rubisco-sfa/ILAMB-Data#30]
The ILAMB data repo does not have GBAF latent and sensible heat flux datasets.

**Comment by nocollier** [comment]
Thanks very much for this report. 

I am not sure where you are looking, in the past we have had conflicting information in different places. Some time ago we moved from referring to this product as GBAF in favor of FLUXCOM. If you look at the recently revamped:

https://www.ilamb.org/datasets.html

you will see that we have FLUXCOM `hfss` and `hfls` fluxes along with `gpp` and respiration. See the parsing script here:

https://github.com/rubisco-sfa/ILAMB-Data/blob/master/FLUXCOM/convert.py

for more information. Does that look correct to you?

**Comment by XUEYANZZZ** [comment]
Hi Rubisco-Sfa/Ilamb-Data,

Thanks for the quick response! GABF is different from FLUXCOM! They are
generated using different methods! I did find FLUXCOM that is not what I
need! Before I did find GBAF and FLUXCOM both in the link you provided, but
not this time! Thanks!

Xueyan

**Comment by nocollier** [comment]
Apologize for the delay in updating this comment. At the moment we are not planning on including more of the products available through the Jena portal. However, if you can register and FTP files locally to your system, then the script found [here](https://github.com/rubisco-sfa/ILAMB-Data/blob/master/FLUXCOM/convert.py) can be used to create a ILAMB-ready file. Sorry! And thanks!
