### ISSUE TITLE
confirm biomass units as carbon versus biomass?

### ISSUE THREAD

**Issue by ckoven** [rubisco-sfa/ILAMB-Data#35]
Hi All -- I was just staring at the various biomass datasets and am struck by the large difference in slope between the ESA Biomass_cci product and others when plotted against each other.  One tricky thing is that sometime biomass is reported in carbon units and sometimes in total biomass, with a factor of two difference. It strikes me that the offset would possibly disappear if the ESA product was actually in units of total biomass rather than carbon. Looking at the variable description at https://catalogue.ceda.ac.uk/uuid/5f331c418e9f4935b8eb1b836f8a91b8 strikes me that that is possibly the case. Is that how ILAMB is currently interpreting the data, or is it converting from biomass to carbon already?

**Comment by ckoven** [comment]
just further noting that in my reading of the ATBD document for the product at https://climate.esa.int/media/documents/D2_2_Algorithm_Theoretical_Basis_Document_ATBD_V3.0_20210614_hkrml_SQ_MS.pdf they make a distinction between AGB and carbon on page 75 of the document, which further suggests that the product itself is not in carbon units.

**Comment by nocollier** [comment]
Thanks for taking a look at this, I am treating the product like the others we have in the category, as if it were carbon. See below for a selection of the data file's global attributes, perhaps it sheds more light. Is there a more appropriate model variable for total biomass that we could compare against?

```
:title = "ESA CCI above-ground biomass product level 4, year 2010" ;
:institution = "GAMMA Remote Sensing" ;
:source = "ALOS-2 PALSAR-2 FB and WB mosaics, Sentinel-1 GRD" ;
:history = "AGB estimation with BIOMASAR-L, v202106, AGB estimation with BIOMASAR-C, v202106, Merging of AGB estimates, v202106" ;
:references = "http://cci.esa.int/biomass" ;
:summary = "This dataset contains a global map of above-ground biomass of the epoch 2010 obtained from L-and C-band spaceborne SAR backscatter, placed onto a regular grid." ;
:keywords = "satellite, observation, forest, biomass" ;
:platform = "ALOS-1, ENVISAT" ;
:sensor = "PALSAR-1, ASAR" ;
:spatial_resolution = "100 m" ;
:key_variables = "agb" ;
```

**Comment by ckoven** [comment]
@nocollier ok that's great.  So, assuming that my reading is correct (which I'll follow up with data providers to confirm) then the widely used conversion factor from biomass to carbon is just to multiply biomass by 0.5 to get the mass of carbon in biomass.  Given that there are two potential sources of mismatch here (aboveground versus aboveground plus belowground and biomass versus carbon in biomass), we should probably check through the provenance of each of the other biomass datasets too to confirm that all are alike?

**Comment by nocollier** [comment]
## Quick Reference

| Identifier    | Region   | Units  | ABG/Total | Uncertainty | Dependencies                           |
| ------------- | -------- | ------ | --------- | ----------- | -------------------------------------- |
| Saatchi2011   | tropical | carbon | total     | yes?        |
| Avitable2016  | tropical | total? | AGB       | no          | Saatchi2011 + Baccini2012 + local data |
| GEOCARBON     | global   | total? | AGB       | no          | Avitable2016 + Santoro2015             |
| Thurner2013   | 30-80N   | carbon | total     | yes         |
| XuSaatchi2021 | global   | carbon | total     | yes?        |
| ESACCI        | global   | total  | ABG       | yes         |

## Avitable2016 (Pan-tropical)

Integrates two maps (Saatchi et al., 2011; Baccini et al., 2012) with  high-quality biomass [local data](http://lucid.wur.nl/storage/downloads/high-carbon-ecosystems/Avitabile_AGB_RefData.zip) into an improved pan-tropical aboveground biomass map of woody vegetation at 1 km resolution for the 2000’s. Data is available for [download](http://lucid.wur.nl/storage/downloads/high-carbon-ecosystems/GEOCARBON_Forest_AGB_Map.zip). Methods are described in their [paper](https://doi.org/10.1111/gcb.13139). 


## GEOCARBON (Global)

Searching around the internet, I found that the GEOCARBON website is broken, but [this](https://www.wur.nl/en/Research-Results/Chair-groups/Environmental-Sciences/Laboratory-of-Geo-information-Science-and-Remote-Sensing/Research/Integrated-land-monitoring/Forest_Biomass.htm) university page comes up which describes several products (including Avitable2016). From what I can tell, it seems they are reporting total above ground biomass.

The GEOCARBON product is generated by combining and harmonizing the Avitabile pan-tropical biomass map with the boreal forest biomass map by Santoro2015. Global [dataset](http://lucid.wur.nl/storage/downloads/high-carbon-ecosystems/GEOCARBON_Forest_AGB_Map.zip) is available. The pdf documentation reads that they are reporting "Aboveground biomass density of vegetation in units of Mg/ha". I didn't find the Santoro2015 dataset, but here is the reference [publication](https://doi.org/10.1016/j.rse.2015.07.005).

I also found a GEOCARBON dataset on the Jena data [portal](https://www.bgc-jena.mpg.de/geodb/projects/Home.php): dataset #201 "Forest Aboveground Biomass Map". It it listed as v3, published in 2015 also by Avitable. This file hosted at Jena is in `netCDF` format and is 171 `Mb` in size. The previous file hosted with LUCID is a zip file containing a `tif` and is about 212 `Mb`. Are they the same? If not which is preferred? No date or version number is provided in the LUCID version.

## Saatchi2011 (Tropical)

Saatchi makes a point of reporting carbon units in his [paper](https://doi.org/10.1073/pnas.1019576108). "The total biomass carbon stock of forests in the study region is estimated to be 247 `Gt C`, with 193 `Gt C` stored aboveground and 54 `Gt C` stored belowground in roots." The samples used to calibrate the satellite signal were collected between 1995-2005.

His paper also mentions the ratio of aboveground biomass to total and provides a citation: "...aboveground biomass, which accounts for 70–90% of forest biomass carbon ([16](https://link.springer.com/article/10.1007/s004420050201))"

The paper shows a plot of uncertainty which would be great to have. However, there is no link to the dataset in the paper nor in the header of the netCDF file that we use. It would be good to revisit this as his paper reports 247 `Gt C` but the sum of what we have in ILAMB now (the Tropical dataset) is 351 `Gt C`. In the notes in the header I see it was regridded back in 2015 and perhaps not in a mass conserving manner. Would be good to revisit.

## Thurner2013 (30N - 80N)

If his [paper](https://doi.org/10.1111/geb.12125), Thurner claims that the data is available on the [biosamar](http://www.biomasar.org/) website (which throws an error for me) and on the GEOCARBON data portal. If it is on either site, I cannot find it. What we have came from a student and I cannot reproduce it.

"This study is based on a recently available growing stock volume (GSV) product retrieved from synthetic aperture radar data. Forest biomass and spatially explicit uncertainty estimates were derived from the GSV using existing databases of wood density and allometric relationships between biomass compartments (stem, branches, roots, foliage)."

## XuSaatchi2021 (Global)

I believe they are reporting total biomass in carbon units based on text in their [paper](https://www.science.org/doi/10.1126/sciadv.abe9829). The data is avaiable on [zenodo](https://zenodo.org/record/4161694#.Yy3EF9LMLd4). There appears to be uncertainty provided (Fig S7) but I am not seeing that in the datafiles. Should this dataset simply replace the Tropical one?

## ESACCI aka Santoro2021 (Global)

Data and documentation available [here](http://dx.doi.org/10.5285/5f331c418e9f4935b8eb1b836f8a91b8). The dataset provides "above ground biomass (AGB, unit: tons/ha i.e., Mg/ha) defined as the mass, expressed as oven-dry weight of the woody parts (stem, bark, branches and twigs) of all living trees excluding stump and roots". I think this means it is above ground biomass in total units.

**Comment by ckoven** [comment]
Also noting that the original source for the US biomass dataset is [here](https://data.fs.usda.gov/geodata/rastergateway/biomass/), which states that it is in biomass.

**Comment by ckoven** [comment]
Yes I think a comparison of all of the datasets against each other, put into units of total vegetation carbon, would be a really helpful check.

**Comment by nocollier** [comment]
I have uploaded an adjusted version of the `cVeg` comparison: [adjusted](https://www.climatemodeling.org/~nate/ILAMB-Test/comparisons/cVeg_adjusted.png) and [original](https://www.climatemodeling.org/~nate/ILAMB-Test/comparisons/cVeg.png). In the adjusted version, there are 3 datasets that have a `*` post-pended to their name: ESACCI, GEOCARBON, and USForest. These all needed their units changed from total biomass to carbon (`* 0.5`) and then their aboveground biomass converted to total (`/ 0.7`). Take a critical look and we can discuss, I am not certain I haven't made a mistake. Neither am I totally happy with magic constants.

Also note:
* `Saatchi2011 = Tropical`
* `GLOBAL.CARBON` was from Saatchi but never had a reference. I have removed it and now we have `XuSaatchi2021`
* I dropped `NBCD2000` for the moment

**Comment by nocollier** [comment]
NBCD2000: https://daac.ornl.gov/NACP/guides/NBCD_2000_V2.html

**Comment by nocollier** [comment]
Note that the comparison [plot](https://www.climatemodeling.org/~nate/ILAMB-Test/comparisons/cVeg_adjusted.png) now includes SpawnGibbs2020. This product is unique in that they combine many other sources (~25) which includes vegetation types other than forests and has an independent estimate of below ground biomass. I have combined them in this plot and uncertainty is provided.
