### ISSUE TITLE
Discussion Points for 2022/08/10 Group Meeting

### ISSUE THREAD

**Issue by nocollier** [rubisco-sfa/ILAMB-Data#36]
- [x] Progress on soil moisture in high latitudes? @jiafumao 
- [x] I have [reviewed](https://github.com/rubisco-sfa/ILAMB/pull/44#pullrequestreview-1062144887) @ypwong22 pull request which includes some changes to the ILAMB library. We need to step through this carefully as there is some logic which assumes things like `noleap` calendars which won't work on other models.
- [x] Are our biomass datasets consistently reporting carbon and not total biomass? See #35 which @ckoven brings up. It seems the new ESACCI product is total which would explain the factor of ~2 difference in the comparison [plots](https://www.climatemodeling.org/~nate/ILAMB-Test/comparisons/cVeg.png). We should check our other products, volunteers?
- [x] I have re-encoded the NCSCD data to produce two products [cSoil](https://www.climatemodeling.org/~nate/ILAMB-Test/comparisons/cSoil.png) and [cSoilAbove1m](https://www.climatemodeling.org/~nate/ILAMB-Test/comparisons/cSoilAbove1m.png). There is a difference in this and the NCSCDV22 product that we encoded long ago, seems to be from interpolation. Is the spatial variability so high that we shouldn't regrid? 
- [x] There are other datasets available as per this ESSD [paper](https://essd.copernicus.org/preprints/essd-2022-232/). Should we chase these down and encode?

**Comment by jiafumao** [comment]
@nocollier , yes, we'll be presenting some initial comparisons between CESM and other products during the ilamb meeting this afternoon.

**Comment by nocollier** [comment]
Biomass:

- [ ] review our biomass data products, do they represent above ground biomass or total? carbon or total biomass?
- [ ] restore the Geocarbon and get the new Saatchi dataset
- [ ] which models have cStem? how does this change our biomass comparisons?
- [ ] loop in @mmu2019 as he and Jim looked at a lot of this a while back

Soil Carbon:

- [ ] loop in @umishra1226 to this discussion
- [ ] We have several datasets encoded, there are others in this ESSD paper, but there is a lot of variance. What products are recommended for our purpose of confronting models?

**Comment by nocollier** [comment]
Update on soil carbon. 

* Umakant provided a perspective that none of the soil carbon products are 'best'
* In terms of spatial distribution, the SoilGrids250 product is somewhat better but not good
* Merging a number of products that do not curate sites for the type of soil carbon will not produce a better estimate
* The soil carbon WG will look at generating a new product with this curation
