### ISSUE TITLE
CERES Albedo has wrong unit

### ISSUE THREAD

**Issue by nocollier** [rubisco-sfa/ILAMB-Data#38]
Shouldn't this line:

https://github.com/mmu2019/Datasets/blob/master/read-albedo-ceres.py#L164

be `1`?

**Comment by mmu2019** [comment]
This code has been updated, but I tried to push the code and update the new file, but the request was denied.

**Comment by nocollier** [comment]
Ok, thanks. I can do it, I just wanted to make sure that I didn't
misunderstand something.

**Comment by mmu2019** [comment]
Great. Thanks.

Mingquan

**Comment by nocollier** [comment]
Looking at this some more, I went to check out the original data. I am
seeing that they have 3 kinds of fluxes:

* All-Sky
* Clear-Sky (for cloud-free areas of region)
* Clear-Sky (for total region)

From your file I cannot tell which ones you used. Here is a talk they
presented on the differences but it isn't completely clear to me which ones
we should use. Do you know? Or should we bring this up to the group?

https://ceres.larc.nasa.gov/documents/STM/2019-05/12_Loeb_EBAF_Talk_Spring2019.pdf

**Comment by nocollier** [comment]
See comparison plots [here](https://www.climatemodeling.org/~nate/ILAMB-Test/comparisons/rns_CERES.png). The plot labeled 'ILAMB' is what we currently have which seems to be very nearly 'AllSky'. The other two options are close to each other but present a non-trivial bias. Which is more fair to models?

**Comment by mmu2019** [comment]
Lines 24 and 25 have mentioned the radiation used is for all sky. Yes, you are right, and we should make it comparable to the models. Thanks to let me know.

**Comment by nocollier** [comment]
Thanks Mingquan, are you saying though that the 'All Sky' is the appropriate quantity to compare against models? Sorry if I am being a little dense, I do not understand all of these issues.

**Comment by mmu2019** [comment]
Yes, I think model radiation data is for all sky.
