### ISSUE TITLE
New Northern Hemisphere Permafrost Map

### ISSUE THREAD

**Issue by climate-dude** [rubisco-sfa/ILAMB-Data#4]
I found a new permafrost map in a June 2019 paper, titled &ldquo;Northern Hemisphere permafrost map based on TTOP modelling for 2000–2016 at 1 km<sup>2</sup> scale&rdquo;, at https://doi.org/10.1016/j.earscirev.2019.04.023

The data are from AWI at https://doi.pangaea.de/10.1594/PANGAEA.888600?format=html#download

We should evaluate the utility of using this product, and start by comparing it with the existing map we have in ILAMB.

**Comment by nocollier** [comment]
This would also be a good motivation to revisit the various techniques of estimating permafrost extent. Dave @dlawrenncar and I have had some email discussions about this. One issue is the technique used to approximate the permafrost table. The other is how to mask out glaciers in a unbiased way. I am thinking we should use a model's glacier fraction (or whatever the variable is) if present and if not, interpolate from CESM or some other agreed upon reference.

**Comment by nocollier** [comment]
https://github.com/rubisco-sfa/ILAMB-Data/tree/master/permafrost
