### ISSUE TITLE
Data issue of `DATA/albedo/CERESed4.1/albedo.nc`

### ISSUE THREAD

**Issue by rhaegar325** [rubisco-sfa/ILAMB-Data#50]
Hi, Rubisco team:
 we get `ILAMB-DATA` by `ilamb-fetch` and found dataset `DATA/albedo/CERESed4.1/albedo.nc` has corrupted. More specifically,  the image we plot is like this:
<img width="588" alt="Screenshot 2023-10-24 at 12 10 32 pm" src="https://github.com/rubisco-sfa/ILAMB-Data/assets/65888230/b1ad87e5-7af4-4da1-880d-cf732100e7f9">
<img width="597" alt="Screenshot 2023-10-24 at 12 10 39 pm" src="https://github.com/rubisco-sfa/ILAMB-Data/assets/65888230/941fd390-e633-4952-9360-3f0bd50573bf">
<img width="593" alt="Screenshot 2023-10-24 at 12 10 46 pm" src="https://github.com/rubisco-sfa/ILAMB-Data/assets/65888230/91d6ffd6-a4c0-4e74-a33e-48b032e914b4">

**Comment by nocollier** [comment]
Thanks for the report. I can reproduce this error but somehow (and it is unclear to me how) the ILAMB results run fine. As CERESed4.2 is available now, I am just going to recode this dataset. Stay tuned.

**Comment by nocollier** [comment]
Data updated: a4c1c57
https://github.com/rubisco-sfa/ILAMB/pull/80
