### ISSUE TITLE
Carbon accumulation potential from regrowth

### ISSUE THREAD

**Issue by climate-dude** [rubisco-sfa/ILAMB-Data#51]
We have a lack of land user and land cover change data sets in ILAMB. We should consider various data sets available and the kind of different metrics required to use them. One data set that looks interesting is this global 1km x 1km 30-year forest regrowth potential carbon accumulation data set available at https://data.globalforestwatch.org/documents/f950ea7878e143258a495daddea90cc0/about

The related paper is at https://www.nature.com/articles/s41586-020-2686-x

This data set was identified in an NGEE Tropics All Hands Meeting breakout session focused on land use on November 15, 2023.

**Comment by ckoven** [comment]
Thanks @climate-dude would be great to discuss how to infer the corresponding information from FATES or other demographic models to use this as a standardized benchmark.

**Comment by climate-dude** [comment]
Yes, @ckoven , let's have that discussion in a future benchmarking dev meeting. It must be more complicated than simply accumulating change in Cveg.

**Comment by ckoven** [comment]
noting that there is an updated version of this dataset is here: https://www.nature.com/articles/s41558-025-02355-5
