### ISSUE TITLE
Conserving Land-Atmosphere Synthesis Suite (CLASS) v1.1

### ISSUE THREAD

**Issue by nocollier** [rubisco-sfa/ILAMB-Data#6]
Gab Abramowitz's group has created a globally gridded dataset which simultaneously balances water and energy while also providing estimates of uncertainty based on agreement with site measurements. We are actively working on adding this dataset to ILAMB and also adapting the methodology to make use of the uncertainty measurements.

This issue is meant to represent current progress and provide a location for further comment. We have:

* [Code](https://github.com/rubisco-sfa/ILAMB-Data/blob/master/CLASS/CLASS_to_ILAMB.py) which automatically downloads and formats the variables.
* A [branch](https://github.com/rubisco-sfa/ILAMB/tree/ncollier/uncert) in the main ILAMB repository which uses the uncertainty estimates and compares to the old methodology. This is currently in development.
* A [webpage](https://www.climatemodeling.org/~nate/CLASS/) where we have the current methodology across the collection of CMIP6 models.

There are a number of open questions to address:

* There is a dataset for the water storage variable that currently is not included. We need a mechanism for skipping the bias score in this new codebase as the storage variable is an anomaly which has a mean of zero.
* There is also a ground heat flux variable provided. I am not sure what variable this maps to in the CMIP table or if models provide it to ESGF.
* We are currently including notions of uncertainty in the scoring of bias and RMSE. Could we develop other areas of the score (phase, spatial distribution, interannual variability) to also make use of the uncertainty?

**Comment by nocollier** [comment]
Dave @dlawrenncar has noticed that this precipitation looks very poor across all models. How does this measure of pr stack up against others? We have decided that running against offline models should provide a better understanding as the precipitation scores should then be quite good.

**Comment by nocollier** [comment]
Update @climate-dude @dlawrenncar :

* I ran offline CLM{4,4.5,5} with {GSPW3,CRUNCEP} through the CLASS suite and the results are [here](https://www.climatemodeling.org/~nate/CLASS/CLM/). Also, see an alternate view of performance below as an image. I have included the change in storage data even though I still score with respect to bias which I think does not make sense with that variable. Adding a skip for this is still on the todo list.
* CLASS provides an estimate of ground heat flux (`hfdsl`) which we currently do not benchmark. Very few CMIP6 models have this uploaded on ESGF and none in historical. For the CLM runs, I grabbed `FGR12` from their 'h0' files (as per Keith) and added it to the CMORized files. 

The following is an attempt at an alternate view of absolute performance of just the uncertainty bias score. Note that the minimum radius is 0.5 just to make variations easier to eyeball. What I like about this style of reporting is that you can see what aspects of the cycle your model is capturing poorly. Plotting these **absolute** scores like this does imply that they are somehow comparable--an issue we have thought about for a while. From my point of view, adding in uncertainty helps make them a bit more comparable in that a good score means that variables are within some notion of the observational uncertainty. However, we still have no sense for how 'poor' score compare. Something to keep in mind.

![CLASS_bias](https://user-images.githubusercontent.com/1331463/78372010-baef2380-7596-11ea-93f9-63d740734322.png)

**Comment by dlawrenncar** [comment]
Thanks Nate,

Interesting that bias score is improved for LH in CLM5 but runoff bias
score is worse.  Also, the biases are both high in global mean (too much LH
and too much runoff).  Points to an inconsistency in the obs/forcing system
somewhere!   Maybe it means the GSWP3 P is wrong or exposes a limitation in
CLASS?  Hmmm.  I guess that CLASS must use some observation P product in
its methods.  I wonder if that data is also available via CLASS.  Should
see that P used in CLASS is higher than in GSWP3 to be able to explain the
high bias in CLM in both LH and runoff.

I noticed that ground heat flux is non-zero across much of the globe in the
annual mean in CLASS.  That doesn't really make sense since, in the absence
of heat storage in the soil due to climate change, annual average ground
heat flux should average to ~0.   I wonder what ground heat flux really
means in CLASS (i.e., does it effectively include heat transfer into the
snow?).  Maybe it does.  Annual mean heat heat flux into soil and snow in
CLM (FGR) shows values that are more consistent with CLASS, though there
are places even in the tropics in CLASS with ground heat flux distinctly
non-zero.  I guess would be interesting to see what the timeseries plots
look like.  Is there a trend that could potentially be related to global
warming ... but I think the values are far too big to really be explained
by global warming.

http://webext.cgd.ucar.edu/I20TR/clm50_r270_1deg_GSWP3V1_iso_newpopd_hist/lnd/clm50_r270_1deg_GSWP3V1_iso_newpopd_hist.1995_2014-clm45_r270_1deg_GSWP3V1_hist.1995_2014/set2/set2_ANN_FGR.png

I like the method to look at scoring.

**Comment by dlawrenncar** [comment]
I looked at what CMIP variables are available for ground heat flux.  I found only hfdsl, which is only requested daily as far as I can tell.  This is the downward heat flux into the ground.  When analyzing this field, it will be important to figure out if the obs are the heat flux into the ground or the heat flux into the surface.  If the surface, then this is means that when there is snow, it accounts for that flux.  If the ground, then it is just the heat flux into the ground, which could be under snow.

**Comment by nocollier** [comment]
Ok, I will lose the water storage term but rename and include the ground heat in `ilamb.cfg` even though for the CMIP6 comparison it will be blank for now. I see data for some land-hist runs so we could include it in that comparison. As you say, the data is daily and so the comparison might be slow. ILAMB will detect that the reference is monthly and coarsen out the model as needed. Let's see what happens.

Another question: what all belongs in what in the paper is `Rn`, the surface net radiation? The paper says 'A key role of the land surface in the climate system is to absorb solar and atmospheric radiation (surface net radiation Rn)' and so I interpreted this as `rns = rlds-rlus+rsds-rsus` (down minus up) but CLASS seems almost universally low relative to other products in our collection:

https://www.climatemodeling.org/~nate/ILAMB-Test/comparisons/rns.png

It makes me wonder if I have this definition correct. Or is this a feature of the CLASS dataset?

**Comment by nocollier** [comment]
I ran a check for how well correlated CLASS `rns` is to all possible combinations of the radiation components from the CERES product. Basically you nest 4 loops and for a scaling of each component by [-1,0,1] and check the correlation of the sum. The best correlation matches the equation `rlds-rlus+rsds-rsus` so I think that CLASS radiation is `rns` and low relative to our other products. They do not have things broken out into components.

**Comment by dlawrenncar** [comment]
OK.  Then I would probably include it for now as an option.  I'd be curious
to see what it looks like in a land-hist comparison, for example.  Does it
show up as an outlier from the other datasets and also all the models (when
forced with obs).  Maybe it is a reasonable alternative reality.  If it
still looks an outlier, then I could inquire with Gab to see what he thinks
... and also should read their paper in more detail.

**Comment by nocollier** [comment]
Integrated. See [this](https://www.ilamb.org/CMIP6/historical/) ILAMB comparison of CMIP6 models. I am going to close this because the dataset is integrated, but there are a few questions left:

* As we discuss above, the CLASS net radiation is low relative to other data products as well as other [models](https://www.ilamb.org/CMIP6/historical/RadiationandEnergyCycle/SurfaceNetRadiation/CLASS/CLASS.html#AllModels). We appear to be comparing to the correct variable, the low bias appears to be a feature. We should followup with Gab and run against `land-hist` runs.
* The current version of ILAMB does not have the uncertainty methodology included. I had some strange trouble encoding the uncertainty and so I dropped it for now. When we launch ILAMBv3, will need to revisit this and encode it properly.
* As of the time of this writing, we have no ground heat flux variable to test, but it is included in the test output.
* Should the CLASS versions of `hfls` and `mrro` deprecate `DOLCE` and `LORA`, respectively? As I understand, they are built on the same methodology with the exception that the CLASS versions are modified with the additional constraint that the budget is closed.
