### ISSUE TITLE
Questions about contribute to ilamb-data collection

### ISSUE THREAD

**Issue by rhaegar325** [rubisco-sfa/ILAMB-Data#60]
Hi, team:

Recently, we would like to contribute to ilamb-data collection, and we would like to know what kind of dataset was accepted:
1. spatial and temporal resolution: is there a min/max for spatial and temporal resolution.
2. point vs gridded datasets: can we have both or is it only gridded datasets?
3. spatial extent: is there any requirements on the overall spatial extent of the dataset? Can it cover any region? Or is there a min. size? we would like to know if it's possible to have Australia-only data in ilamb-data.
4. Is it possible to add urban specific datasets in ILAMB-data?

**Comment by msteckle** [comment]
Great to hear! See this tutorial for some guidance: [format data tutorial](https://www.ilamb.org/doc/format_data.html). Please also reference recent scripts to see how we pre-process, such as these gridded datasets: [convert GFW](https://github.com/rubisco-sfa/ILAMB-Data/blob/master/GFW/convert.py), [convert FLUXCOM](https://github.com/rubisco-sfa/ILAMB-Data/blob/master/FLUXCOM/convert.py) or this point dataset: [convert Ameriflux](https://github.com/rubisco-sfa/ILAMB-Data/blob/master/Ameriflux/Diurnal/AMFtoNetCDF4.py)

1. We spatially resample gridded data to 0.5 degree resolution (EPSG:4326), which with spatially global bounds is a netcdf with 720 x 360 cells. There are not time constraints, but applicable time bounds (e.g., 1950 to 2020) must be specified in the netcdf you create.
2. ILAMB can handle point and gridded datasets. ILAMB will sample the model grid at each point for comparison. See the Ameriflux example I linked above.
3. There is no spatial extent requirement for the benchmark dataset. For example, here, you can see that the bias and bias scores are spatially constrained to the extent of the benchmark data: https://www.ilamb.org/CMIP5v6/historical/EcosystemandCarbonCycle/Biomass/Tropical/Tropical.html
4. Yes, if there is an urban-specific variable from the benchmark dataset that corresponds to an urban-specific variable in the land model you're comparing to, then you can do so.

In general, be sure to format your netcdf using [CF Conventions](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html) and, if possible, format variable names according to [CMIP6 variables grouped by MIP table](https://clipc-services.ceda.ac.uk/dreq/index/var.html) or [all accepted CMIP6 variables](https://clipc-services.ceda.ac.uk/dreq/index/var.html).

To contribute to this repo: 
1. Create a new issue with a description of the benchmark dataset you'd be adding, plus any links or useful information in the body and some explanation for why it's a useful bench-marking dataset
2. Fork from ILAMB-Data
3. Create a new folder to work in (we generally name it after the folks/project who made the dataset; name it whatever you like)
4. Write your convert file inside the folder you created
5. When finished, submit a pull request for us to review
