### ISSUE TITLE
Data for a Soil Respiration (Rs) Confrontation

### ISSUE THREAD

**Issue by climate-dude** [rubisco-sfa/ILAMB-Data#61]
A variety of ML-based extrapolations of in situ measurements aggregated primarily by Ben Bond-Lamberty are now available. The latest paper I have found that has produced some kind of globally gridded soil respiration maps is this one:

Liu, J., Hu, J., Liu, H. et al. Global soil respiration estimation based on ecological big data and machine learning model. Sci Rep 14, 13231 (2024). https://doi.org/10.1038/s41598-024-64235-w

We should evaluate a few of them and incorporate at least one into ILAMB.

**Comment by msteckle** [comment]
> A variety of ML-based extrapolations of in situ measurements aggregated primarily by Ben Bond-Lamberty are now available. The latest paper I have found that has produced some kind of globally gridded soil respiration maps is this one:
> 
> Liu, J., Hu, J., Liu, H. et al. Global soil respiration estimation based on ecological big data and machine learning model. Sci Rep 14, 13231 (2024). https://doi.org/10.1038/s41598-024-64235-w
> 
> We should evaluate a few of them and incorporate at least one into ILAMB.

Seems this data from Liu 2024 is only available on request. Looked into Ben's global soil respiration database and he created 1km gridded data products in 2020: https://daac.ornl.gov/CMS/guides/CMS_Global_Soil_Respiration.html
