### ISSUE TITLE
CERESed4.1 datasets not accessible

### ISSUE THREAD

**Issue by ph-kev** [rubisco-sfa/ILAMB-Data#71]
On [https://www.ilamb.org/datasets.html](https://www.ilamb.org/datasets.html), any CERESed4.1 datasets are not downloadable and gives the generic message that the requested file was not found on this server.

Is there any way to access these datasets?

**Comment by msteckle** [comment]
We will check out those broken links, thanks for pointing them out.

**Comment by msteckle** [comment]
@ph-kev The datasets have been updated to CERESSed4.2; that's why the links were broken. Check out the new links on https://www.ilamb.org/datasets.html
